imports:
    - { resource: parameters.php }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: session_config.php }
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

# Twig Configuration
twig:
    debug:            true
    strict_variables: %kernel.debug%
    cache: false

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        scssphp:
            apply_to: "\.scss$"
            compass: true

        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

services:
    twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }
