imports:
    - { resource: parameters.php }
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: debug
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

# Assetic Configuration
assetic:
    use_controller: true
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
