<?php

namespace Evp\Bundle\DeviceApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Evp\Bundle\DeviceApiBundle\Entity\TicketExaminer;

/**
 * TicketExaminerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketExaminerRepository extends EntityRepository
{
    /**
     * Finds one ticket examiner person by his unique token
     *
     * @param string $token
     * @return TicketExaminer
     */
    public function findOneByToken($token) {
        return $this->findOneBy(
            array('token' => $token)
        );

    }
}
